### PR TITLE
Cleanup and code refactoring

### PR DESCRIPTION
**Pull request by l-huisman**
This pull request includes several code changes aimed at cleaning up the codebase and improving code quality. The changes include:

- Updating imports and removing unused imports

- Renaming variables and functions for clarity

- Removing commented-out code

- Reorganizing code into logical sections

- Fixing formatting and indentation issues

These changes improve the readability and maintainability of the codebase.

### CODE REVIEW

**Review by TimV22 — APPROVED** [review]
Good job, Jesper slecht bezig. Waarom geen naming standaarden

**Comment by CaptainJeppie** [comment]
idc

**Comment by TimV22** [comment]
> idc

You should

**Comment by CaptainJeppie** [comment]
> > idc
> 
> You should

well fack you

**Pull request merged**
